#========================================
# Unit test specific settings
#========================================
#----------------------------------------
# Camunda
#----------------------------------------
camunda:
  bpm:
    client:
      base-url: base-url
    deployment:
      autoDeployEnabled: false
      processes:
        - name: process_name_1
          tenant: tenant_id_1
          bpmnResourcePattern: bpmnResourcePattern_1
          dmnResourcePattern: dmnResourcePattern_1
          formResourcePattern: formResourcePattern_1
        - name: process_name_2
          tenant: tenant_id_2
          bpmnResourcePattern: bpmnResourcePattern_2
          dmnResourcePattern: dmnResourcePattern_2
          formResourcePattern: formResourcePattern_2

#----------------------------------------
# Camunda integration settings
#----------------------------------------
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: camunda.url